version: 2.1

orbs:
  composer: stockfiller/composer@1.0.0
  node: circleci/node@4.1

jobs:
  lint-js:
    docker:
      - image: cimg/node:14.18.3
    steps:
      - checkout
      - node/install-packages
      - run:
          working_directory: js
          command: npm run lint:js
workflows:
  js-flow:
    jobs:
      - lint-js
