name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-all:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Lint all files
      run: npm ci
    - name: Running the linting
      run: npm run lint:js
